imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CoreBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    version: 1.0
    app.path.user_images: /uploads/images/users

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    
fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    AD\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        jsqueeze:   ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            
vich_uploader:
    db_driver: orm
    mappings:
        user_images:
            uri_prefix:         '%app.path.user_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/users'
            
easy_admin:
    site_name: 'Website Name'
    design:
        brand_color: '#1ABC9C'
        color_scheme: 'dark'
        assets:
            favicon: '/assets/backend/favicon.png'
            css:
                #look here to find the ids for the css: https://symfony.com/doc/current/bundles/EasyAdminBundle/book/design-configuration.html
                # HTTP protocol-relative URL
                #- '//example.org/css/admin1.css'
            js:
                #Same as css
    entities:
        User:
            class: AD\UserBundle\Entity\User
            translation_domain: 'user'
            label: user.label
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image', label:'property.imageFile' }
                    - { property: 'username', label: 'property.username' }
                    - { property: 'email', label: 'property.email' }
            list:
                title: user.list.label
                max_results: 10
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.user_images%', label: 'property.image' }
                    - { property: 'id', label: 'property.id' }
                    - { property: 'username', label: 'property.username' }
                    - { property: 'email', label: 'property.email' }
                    - { property: 'roles', label: 'property.roles' }
                    - { property: 'enabled', type: 'boolean', label: 'property.enabled' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.user_images%' }
            search: #https://symfony.com/doc/current/bundles/EasyAdminBundle/book/list-search-show-configuration.html
                fields:
                    - { property: 'username', label: 'property.username' }
                    - { property: 'email', label: 'property.email' }
